spring:
  mvc:
    view:
      prefix: /WEB-INF/page/
      suffix: .jsp
  devtools:
    restart:
      enabled: true
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/, classpath:/static/, classpath:/public/, file:${upload.dir} # 这里增加了一种配置上传路径的方法，直接设置为静态资源路径

upload:
  dir: E:/CMUPLOAD/
